package com.tramite.online.domain.type;

public enum QuestionType {
   QUESTION_TEXT,
   QUESTION_RADIO,
   QUESTION_CHECKBOX,
   QUESTION_SELECT,
   QUESTION_NUMBER,
   QUESTION_DATE,
   QUESTION_FILE,
   QUESTION_TEXTAREA,
   QUESTION_SELECT_MULTIPLE,
   QUESTION_RADIO_MULTIPLE
}
