server:
    port: ${PORT:8080}

spring:
    application:
        name: project-tramite-online
        page-size: 10
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
        open-in-view: false
        show-sql: true
    security:
        user:
            name: dgarcia
            password: 123456
        oauth2:
         client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope:
                - email
                - profile
            github:
              client-id: ${GITHUB_CLIENT_ID}
              client-secret: ${GITHUB_CLIENT_SECRET}
         
         
application:
  page-size: 10
  jwtSecret: tu_secreto_aqui
  jwtExpiration: 3600000
  jwtRefreshToken: 86400000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:4200/oauth2/redirect
      - http://localhost:3000/oauth2/redirect  # Si usas React/Vue

management:
    info:
        git:
            mode: full
    endpoints:
        web:
            exposure:
                include: "*"
    metrics:
        tags:
            application: ${spring.application.name}
    tracing:
        enabled: false
        sampling:
            probability: 1.0


# Configuration logger
# logging:
#   structured:
#     format:
#       console: ecs

# Configuration redis
# spring:
#   redis:
#     host: localhost
#     port: 6379
#     password: 
#     database: 0
